# Generated by Django 3.2.5 on 2021-08-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='status',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
