# Generated by Django 3.2.5 on 2021-09-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_space_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
