# Generated by Django 3.2.5 on 2021-09-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_space_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='email',
            field=models.EmailField(default='d', max_length=254),
            preserve_default=False,
        ),
    ]
