# Generated by Django 3.2.5 on 2021-08-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
